# NumPy Review Challenge

To review some basic concepts, attempt to perform these basic NumPy tasks on your own.

### **NAME** : OTABIL ISHAQUE
### **EMAIL** : ishaqueotabi44@gmail.com

Import numpy as np and check your version.

In [1]:
import numpy as np
np.version.version # or print(np.__version__)

'1.26.4'

**Q1:** Create a 1D array of numbers from `0` to `9` and save it as `Q1`.

In [5]:
#Creating 1D array of numbers 0 to 9
Q1= np.array(np.arange(0,10))
Q1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#answer

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Q2:** Create a 1D array of numbers from `10` to `49` and save it as `Q2`.

In [6]:
# Creating a 1D array of numbers from 10 to 49
Q2 = np.array(np.arange(10,50))
Q2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
#answer

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**Q3:** Copy the `Q2` array and save it as `Q3`.  Reverse the values in the `Q3` array (first element becomes the last).

In [27]:
Q3 = Q2.copy()
Q3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [4]:
#Answer

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Q4:** Create a `3x3` matrix with values ranging from `1` to `9` and save it as `Q4`.

In [33]:
Q4 = np.arange(1,10)
Q4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#answer

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Q5:** Set a random seed of `42`. Create a `10x5` array with random values and save it as `Q5`.  Use [np.random.random()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html#).  As a check, your first row of the array should be: `[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864]`

In [37]:
# random seed
np.random.seed(42)
Q5 = np.random.random(50).reshape(10,5)
Q5

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
       [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998],
       [0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446]])

In [6]:
#answer

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
       [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998],
       [0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446]])

**Q6:** Find the minimum and maximum values of above `Q5` array, rounding them to 4 decimal places.  Call the values `Q6A` and `Q6B` respectively. 

In [44]:
Q6A = np.round(Q5.min(),4)
Q6B = np.round(Q5.max(),4)

In [45]:
Q6A

0.0206

In [46]:
Q6B

0.9699

In [7]:
#answer
Q6A

0.0206

In [8]:
#answer
Q6B

0.9699

**Q7:** Find the mean value for the above `Q5` array, rounding to 4 decimal places.  Call this value `Q7`.

In [49]:
Q7 = np.round(Q5.mean(),4)
Q7

0.4459

In [9]:
#answer
Q7

0.4459

**Q8:** Select all even numbers from the following array and call this output `Q8`.
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Q8 = arr[ arr % 2 == 0]
Q8

array([0, 2, 4, 6, 8])

In [10]:
#answer
Q8

array([0, 2, 4, 6, 8])

**Q9:** Make a copy of the `arr` array and call it `Q9`.  Replace all even numbers from `Q9` with `0`.

In [62]:
Q9 = arr.copy()
Q9[ Q9 % 2 == 0] = 0
Q9

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [11]:
#answer
Q9

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

**Q10:** Use the [where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) method to replace all odd numbers from the above `Q9` array with a `-1` and call it `Q10`.

In [72]:
Q10 = np.where(Q9 % 2 != 0,-1,Q9)
Q10

array([ 0, -1,  0, -1,  0, -1,  0, -1,  0, -1])

In [12]:
#answer 
Q10

array([ 0, -1,  0, -1,  0, -1,  0, -1,  0, -1])

**Q11** Reshape the above `arr` array to a `2x5` array and call it `Q11`.

In [73]:
Q11 = Q10.reshape(2,5)
Q11

array([[ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1]])

In [13]:
#answer
Q11

array([[ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1]])

**Q12:** Stack `arr1` and `arr2` (both given below) vertically and call this array `Q12`.

In [89]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.arange(10,20).reshape(2,5)

In [90]:
Q12 = np.vstack((arr1,arr2))
Q12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
#answer
Q12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Q13:** Stack `arr1` and `arr2` horizontally and call this array `Q13`.

In [92]:
Q13 = np.hstack((arr1,arr2))
Q13

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [15]:
#answer
Q13

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

**Q14:** Swap the first and second columns in the following array called `arr3` and save it as `Q14`.

In [184]:
arr3 = np.array([[22, 56, 34],[54, 12, 42],[67, 56, 99]])
arr3[:,[0,1]] = arr3[:,[1,0]]
Q14 = arr3
Q14

array([[56, 22, 34],
       [12, 54, 42],
       [56, 67, 99]])

In [185]:
#answer
Q14

array([[56, 22, 34],
       [12, 54, 42],
       [56, 67, 99]])

**Q15:** Swap rows 1 and 2 in the above `Q14` array and call it `Q15`.

In [186]:

Q14[[0,1],:] = Q14[[1,0],:]
Q15 = Q14
Q15

array([[12, 54, 42],
       [56, 22, 34],
       [56, 67, 99]])

In [188]:
#answer
Q15

array([[12, 54, 42],
       [56, 22, 34],
       [56, 67, 99]])

**Q16:** Next, reverse the columns of the above `Q15` array and call it `Q16`.

In [189]:

Q15[:,[0,1,2]] = Q15[:,[2,1,0]]
Q16 = Q15
Q16

array([[42, 54, 12],
       [34, 22, 56],
       [99, 67, 56]])

In [190]:
#answer
Q16

array([[42, 54, 12],
       [34, 22, 56],
       [99, 67, 56]])

**Q17:** Sort each row of the above `Q16` array from least to greatest and call it `Q17`.

In [195]:
Q17 = np.sort(Q16,axis=1)

In [196]:
Q17

array([[12, 34, 54],
       [22, 42, 56],
       [56, 67, 99]])

In [20]:
#answer
Q17

array([[12, 42, 54],
       [22, 34, 56],
       [56, 67, 99]])

**Q18:** Sort each column of the above `Q17` array from the least to the greatest and call it `Q18`.

In [199]:
Q18 = np.sort(Q17,axis=0)

In [200]:
Q18

array([[12, 34, 54],
       [22, 42, 56],
       [56, 67, 99]])

In [201]:
#answer
Q18

array([[12, 34, 54],
       [22, 42, 56],
       [56, 67, 99]])

**Q19:** Create a `1D` array called `Q19` of `100` values that range evenly between `[1 - 200]`.


In [204]:
Q19 = np.linspace(1,200,100)

In [22]:
#answer
Q19

array([  1.        ,   3.01010101,   5.02020202,   7.03030303,
         9.04040404,  11.05050505,  13.06060606,  15.07070707,
        17.08080808,  19.09090909,  21.1010101 ,  23.11111111,
        25.12121212,  27.13131313,  29.14141414,  31.15151515,
        33.16161616,  35.17171717,  37.18181818,  39.19191919,
        41.2020202 ,  43.21212121,  45.22222222,  47.23232323,
        49.24242424,  51.25252525,  53.26262626,  55.27272727,
        57.28282828,  59.29292929,  61.3030303 ,  63.31313131,
        65.32323232,  67.33333333,  69.34343434,  71.35353535,
        73.36363636,  75.37373737,  77.38383838,  79.39393939,
        81.4040404 ,  83.41414141,  85.42424242,  87.43434343,
        89.44444444,  91.45454545,  93.46464646,  95.47474747,
        97.48484848,  99.49494949, 101.50505051, 103.51515152,
       105.52525253, 107.53535354, 109.54545455, 111.55555556,
       113.56565657, 115.57575758, 117.58585859, 119.5959596 ,
       121.60606061, 123.61616162, 125.62626263, 127.63

**Q20:** Reshape `Q19` to a `25x4` array and call it `Q20`.

In [206]:
Q20 = Q19.reshape(25,4)

In [23]:
#answer
Q20

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [  9.04040404,  11.05050505,  13.06060606,  15.07070707],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 25.12121212,  27.13131313,  29.14141414,  31.15151515],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 41.2020202 ,  43.21212121,  45.22222222,  47.23232323],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

**Q21:** Index the first row of `Q20` and save this as `Q21`.

In [209]:
Q21 = Q20[0]

In [25]:
#answer
Q21

array([1.        , 3.01010101, 5.02020202, 7.03030303])

**Q22:** Index the second column of `Q20` and save this as `Q22`.

In [211]:
Q22 = Q20[:,1]

In [212]:
#answer
Q22

array([  3.01010101,  11.05050505,  19.09090909,  27.13131313,
        35.17171717,  43.21212121,  51.25252525,  59.29292929,
        67.33333333,  75.37373737,  83.41414141,  91.45454545,
        99.49494949, 107.53535354, 115.57575758, 123.61616162,
       131.65656566, 139.6969697 , 147.73737374, 155.77777778,
       163.81818182, 171.85858586, 179.8989899 , 187.93939394,
       195.97979798])

**Q23:** Index every other row of `Q20` starting from the first and save this as `Q23`.

In [223]:
Q23 = Q20[[0,2,4,6,8,10,12,14,16,18,20,22,24],:]

In [27]:
#answer
Q23

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [129.64646465, 131.65656566, 133.66666667, 135.67676768],
       [145.72727273, 147.73737374, 149.74747475, 151.75757576],
       [161.80808081, 163.81818182, 165.82828283, 167.83838384],
       [177.88888889, 179.8989899 , 181.90909091, 183.91919192],
       [193.96969697, 195.97979798, 197.98989899, 200.        ]])

**Q24:** Index the 3rd, 5th and 7th row of the `Q20` array can save this as `Q24`.

In [222]:
Q24 = Q20[[2,4,6],:]

In [29]:
#answer
Q24

array([[17.08080808, 19.09090909, 21.1010101 , 23.11111111],
       [33.16161616, 35.17171717, 37.18181818, 39.19191919],
       [49.24242424, 51.25252525, 53.26262626, 55.27272727]])

**Q25:** Copy the `Q20` array and save it as `Q25`.  Select only the values below 50 from `Q25`, add 5 to these values, and then multiply by 2. The other values should remain unchanged and everything should be saved back to `Q25`.

In [280]:
Q25 = Q20.copy()
Q25 = np.array(Q25)
update = Q25 < 50
Q25[update] = (Q25[update] + 5)* 2


In [30]:
#answer
Q25

array([[ 12.        ,  16.02020202,  20.04040404,  24.06060606],
       [ 28.08080808,  32.1010101 ,  36.12121212,  40.14141414],
       [ 44.16161616,  48.18181818,  52.2020202 ,  56.22222222],
       [ 60.24242424,  64.26262626,  68.28282828,  72.3030303 ],
       [ 76.32323232,  80.34343434,  84.36363636,  88.38383838],
       [ 92.4040404 ,  96.42424242, 100.44444444, 104.46464646],
       [108.48484848,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

**Q26:** Add `Q20` and `Q25` and call the new array `Q26`.

In [283]:
Q26 = np.add(Q20,Q25)

In [31]:
#answer
Q26

array([[ 13.        ,  19.03030303,  25.06060606,  31.09090909],
       [ 37.12121212,  43.15151515,  49.18181818,  55.21212121],
       [ 61.24242424,  67.27272727,  73.3030303 ,  79.33333333],
       [ 85.36363636,  91.39393939,  97.42424242, 103.45454545],
       [109.48484848, 115.51515152, 121.54545455, 127.57575758],
       [133.60606061, 139.63636364, 145.66666667, 151.6969697 ],
       [157.72727273, 102.50505051, 106.52525253, 110.54545455],
       [114.56565657, 118.58585859, 122.60606061, 126.62626263],
       [130.64646465, 134.66666667, 138.68686869, 142.70707071],
       [146.72727273, 150.74747475, 154.76767677, 158.78787879],
       [162.80808081, 166.82828283, 170.84848485, 174.86868687],
       [178.88888889, 182.90909091, 186.92929293, 190.94949495],
       [194.96969697, 198.98989899, 203.01010101, 207.03030303],
       [211.05050505, 215.07070707, 219.09090909, 223.11111111],
       [227.13131313, 231.15151515, 235.17171717, 239.19191919],
       [243.21212121, 247

**Q27:** What is the `shape` of `Q26`?  Save this as `Q27`.

In [287]:
Q27 = Q26.shape

In [32]:
#answer
Q27

(25, 4)

**Q28:** Cast `Q26` array as an `int64` data type.  Save this as `Q28`. What happens to the values?

In [292]:
Q28 = Q26.astype(dtype='int64')

In [33]:
#answer
Q28

array([[ 13,  19,  25,  31],
       [ 37,  43,  49,  55],
       [ 61,  67,  73,  79],
       [ 85,  91,  97, 103],
       [109, 115, 121, 127],
       [133, 139, 145, 151],
       [157, 102, 106, 110],
       [114, 118, 122, 126],
       [130, 134, 138, 142],
       [146, 150, 154, 158],
       [162, 166, 170, 174],
       [178, 182, 186, 190],
       [194, 198, 203, 207],
       [211, 215, 219, 223],
       [227, 231, 235, 239],
       [243, 247, 251, 255],
       [259, 263, 267, 271],
       [275, 279, 283, 287],
       [291, 295, 299, 303],
       [307, 311, 315, 319],
       [323, 327, 331, 335],
       [339, 343, 347, 351],
       [355, 359, 363, 367],
       [371, 375, 379, 383],
       [387, 391, 395, 400]], dtype=int64)

**Q29:** 
- Make a copy of the `Q28` array and call it `Q29`.  
- Select the first value in the first 5 rows in `Q29` and call this slice `arr_slice`.
- Update the second value in `arr_slice` to `42`. Before you check the results, will this update `Q29` or will it remain unchanged?

In [307]:
##Yes This will Update Q9
Q29 = Q28.copy()
arr_slice = Q29[:5,0]
arr_slice[1] = 42

In [102]:
#answer
Q29

array([[ 13,  19,  25,  31],
       [ 42,  43,  49,  55],
       [ 61,  67,  73,  79],
       [ 85,  91,  97, 103],
       [109, 115, 121, 127],
       [133, 139, 145, 151],
       [157, 102, 106, 110],
       [114, 118, 122, 126],
       [130, 134, 138, 142],
       [146, 150, 154, 158],
       [162, 166, 170, 174],
       [178, 182, 186, 190],
       [194, 198, 202, 206],
       [210, 214, 218, 222],
       [226, 230, 234, 238],
       [242, 246, 250, 254],
       [258, 262, 266, 270],
       [274, 278, 282, 286],
       [290, 294, 298, 302],
       [306, 310, 314, 318],
       [322, 326, 330, 334],
       [338, 342, 346, 350],
       [354, 358, 362, 366],
       [370, 374, 378, 382],
       [386, 390, 394, 398]])

**Q30:** Set all negative values in the `data` array (given below) to `0`.  For this exercise you will be updating the actual `data` array.

In [1]:
## Creating the data array
data = np.array([  2,   -4,   8,  16,   -32,   -64, 128])
data = np.where(data < 0,0,data)

NameError: name 'np' is not defined

In [37]:
#answer

array([  2,   0,   8,  16,   0,   0, 128])

Good work!